Added GitInfo
Minor edits

diff --git a/.github/workflows/continuous-build.yaml b/.github/workflows/continuous-build.yaml
--- a/.github/workflows/continuous-build.yaml
+++ b/.github/workflows/continuous-build.yaml
@@ -11,7 +11,12 @@ jobs:
     
     - uses: actions/checkout@v2
     
-    - name: Setup .NET Core
+    - name: Setup .NET Core 3.1
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: '3.1.x'
+
+    - name: Setup .NET 5
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: '5.0.x'
@@ -20,4 +25,12 @@ jobs:
       run: dotnet build --configuration Release
       
     - name: Generate coverage report
-      run: dotnet test --collect "XPlat Code Coverage" --results-directory "./test-results"
+      run: dotnet test --logger "trx;LogFileName=test-results.trx" --collect "XPlat Code Coverage" --results-directory "./test-results"
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: XUnit Tests
+        path: test-results/*.trx    # Path to test results
+        reporter: dotnet-trx       # Format of test results
